<?php
//////////////////////////////////////
// ESYS 2.0 FORMS

//////////////////////////////////////
$formular_15 = '
<form name="form_15" class="formz" method="post">
<br/><br/>
<div class="rowAB">
<div class="colA2"><strong>Tillfälle '.$settillfalle.'</strong></div>
<div class="colB2"><span class="numbers">
5 &nbsp; &nbsp; &nbsp;
4 &nbsp; &nbsp; &nbsp;
3 &nbsp; &nbsp; &nbsp;
2 &nbsp; &nbsp; &nbsp;
1 </span></div>
</div>
<br/>
<div class="rowAB">
<div class="colA2">1. Hur mår du fysiskt?</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f1" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f1" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f1" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f1" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f1" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">2. Hur mår du socialt?</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f2" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f2" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f2" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f2" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f2" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">3. Hur ofta är du stressad?</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f3" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f3" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f3" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f3" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f3" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">4. Hur ofta tränar du?</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f4" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f4" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f4" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f4" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f4" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">5. Hur är din sömn?</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f5" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f5" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f5" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f5" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f5" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">6. Hur är dina matvanor?</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f6" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f6" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f6" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f6" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f6" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">7. Kroppssammansättningstest</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f7" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f7" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f7" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f7" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f7" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">8. Rörlighetstest</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f8" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f8" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f8" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f8" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f8" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">9. Konditionstest</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f9" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f9" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f9" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f9" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f9" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">10. Styrketest</div>
<div class="colB2">
<input class="inputradio" type="radio" name="f10" value="8"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f10" value="6.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f10" value="5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f10" value="3.5"> &nbsp; &nbsp;
<input class="inputradio" type="radio" name="f10" value="2"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">11. Watt (endast siffror)</div>
<div class="colB2">
<input class="inputnum" type="text" name="f11" value=""> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">12. Arbetspuls (endast siffror)</div>
<div class="colB2">
<input class="inputnum" type="text" name="f12" value=""> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">13. Kroppsvikt i kg (endast siffror och decimaler, t ex 70.0)</div>
<div class="colB2">
<input class="inputnum" type="text" name="f13" value=""> &nbsp; &nbsp;</div>
</div>
<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="GruppID" value="'.$GruppID.'"/>
<input type="hidden" name="AnvID" value="'.$AnvID.'"/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="insert"/>
<input type="button" class="submit" onclick="document.form_15.submit()" value="Spara ny sammanställning"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';
//////////////////////////////////////


//////////////////////////////////////
if($action == "formular_edit"){

$arr = array(8,6.5,5,3.5,2);

for ($x = 1; $x <= 10; $x++) {
$fr = 'fr'.$x;
$ff = 'f'.$x;
foreach($arr as $i) {
$$fr .= '<input class="inputradio" type="radio" name="f'.$x.'"';
$$fr .= ($$ff == $i) ? 'checked="checked" value="'.$i.'"' : 'value="'.$i.'"';
$$fr .= '> &nbsp; &nbsp;
';
}
}
}
//////////////////////////////////////
$formular_edit_15 = '
<a name="a_15"/>
<form name="form_15" class="formz" method="post">
<br/><br/>
<div class="rowAB">
<div class="colA2"><strong>Ändra Tillfälle '.$_GET['Tillfalle'].'</strong></div>
<div class="colB2"><span class="numbers">
5 &nbsp; &nbsp; &nbsp;
4 &nbsp; &nbsp; &nbsp;
3 &nbsp; &nbsp; &nbsp;
2 &nbsp; &nbsp; &nbsp;
1 </span></div>
</div>
<br/>
<div class="rowAB">
<div class="colA2">1. Hur mår du fysiskt?</div>
<div class="colB2">
'.$fr1.' </div>
</div>

<div class="rowAB">
<div class="colA2">2. Hur mår du socialt?</div>
<div class="colB2">
'.$fr2.' </div>
</div>

<div class="rowAB">
<div class="colA2">3. Hur ofta är du stressad?</div>
<div class="colB2">
'.$fr3.' </div>
</div>

<div class="rowAB">
<div class="colA2">4. Hur ofta tränar du?</div>
<div class="colB2">
'.$fr4.' </div>
</div>

<div class="rowAB">
<div class="colA2">5. Hur är din sömn?</div>
<div class="colB2">
'.$fr5.' </div>
</div>

<div class="rowAB">
<div class="colA2">6. Hur är dina matvanor?</div>
<div class="colB2">
'.$fr6.' </div>
</div>

<div class="rowAB">
<div class="colA2">7. Kroppssammansättningstest</div>
<div class="colB2">
'.$fr7.' </div>
</div>

<div class="rowAB">
<div class="colA2">8. Rörlighetstest</div>
<div class="colB2">
'.$fr8.' </div>
</div>

<div class="rowAB">
<div class="colA2">9. Konditionstest</div>
<div class="colB2">
'.$fr9.' </div>
</div>

<div class="rowAB">
<div class="colA2">10. Styrketest</div>
<div class="colB2">
'.$fr10.' </div>
</div>
<div class="rowAB">
<div class="colA2">11. Watt (endast siffror)</div>
<div class="colB2">
<input class="inputnum" type="text" name="f11" value="'.$f11.'"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">12. Arbetspuls (endast siffror)</div>
<div class="colB2">
<input class="inputnum" type="text" name="f12" value="'.$f12.'"> &nbsp; &nbsp;</div>
</div>
<div class="rowAB">
<div class="colA2">13. Kroppsvikt i kg (endast siffror och decimaler, t ex 70.2)</div>
<div class="colB2">
<input class="inputnum" type="text" name="f13" value="'.$f13.'"> &nbsp; &nbsp;</div>
</div>
<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="GruppID" value="'.$GruppID.'"/>
<input type="hidden" name="AnvID" value="'.$AnvID.'"/>
<input type="hidden" name="Anvnamn" value="'.$Anvnamn.'"/>
<input type="hidden" name="CSID" value="'.$CSID.'"/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="update"/>
<input type="button" class="submit" onclick="document.form_15.submit()" value="Spara ändrad sammanställning"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

//////////////////////////////////////
$formular_18 = '
<a name="a_18"/>
<form name="form_18" class="formz" method="post">
<br/><br/>
<strong>Skapa ny coach</strong><br/><br/>

<div class="rowAB">
<div class="colA2">Coachnamn</div>
<div class="colB2"><input type="text" name="coachnamn" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Coachlogin</div>
<div class="colB2">
<input type="text" name="coachlogin" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Coachlösenord</div>
<div class="colB2"><input type="text" name="coachlosen" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Coachemail</div>
<div class="colB2"><input type="text" name="coachemail" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Coachens språk</div>
<div class="colB2"><input type="text" name="langs" value="sv"/></div>
</div>

<div class="rowAB">
<div class="colA2">Bild</div>
<div class="colB2">
<input name="file" type="hidden" value="'.$coacher_file.'"/>
<a title="Lägg till bild" class="formbut" href="#" onclick="imagewin(\'images.php?action=getfile&whatform=form_18&basedir=&directory=bilder&area=file&pre_cell=file_cell\');return false;">Lägg till bild</a>
<a title="Ta bort bild" class="formbut" name="rfile" href="#rfile" onclick="document.form_18.file.value=\'\';document.file_cell.src=\'img/blank.gif\'">Ta bort bild</a>
<br/>
<img name="file_cell" src="../magick.php/'.$coacher_file.'?resize(135x150)"/>
</div>
</div>

<div class="rowAB">
<div class="colA2">Svensk presentation</div>
<div class="colB2x"><textarea name="sv_text" class="coachtext" onfocus="document.form_18.sv_text.style.height=\'210px\';document.form_18.en_text.style.height=\'210px\'" onblur="document.form_18.sv_text.style.height=\'30px\';document.form_18.en_text.style.height=\'30px\'"></textarea></div>
</div>

<div class="rowAB">
<div class="colA2">Engelsk presentation</div>
<div class="colB2x"><textarea name="en_text" class="coachtext" onfocus="document.form_18.sv_text.style.height=\'210px\';document.form_18.en_text.style.height=\'210px\'" onblur="document.form_18.sv_text.style.height=\'30px\';document.form_18.en_text.style.height=\'30px\'"></textarea></div>
</div>

<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="insert"/>
<input type="button" class="submit" onclick="document.form_18.submit()" value="Spara ny Coach"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

//////////////////////////////////////
$formular_edit_18 = '
<a name="a_18"/>
<form name="form_18" class="formz" method="post">
<br/><br/>
<strong>Ändra '.$coacher_coachnamn.'</strong><br/><br/>

<div class="rowAB">
<div class="colA2">Coachnamn</div>
<div class="colB2"><input type="text" name="coachnamn" value="'.$coacher_coachnamn.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Coachlogin</div>
<div class="colB2">
<input type="text" name="coachlogin" value="'.$coacher_coachlogin.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Coachlösenord</div>
<div class="colB2"><input type="text" name="coachlosen" value="'.$coacher_coachlosen.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Coachemail</div>
<div class="colB2"><input type="text" name="coachemail" value="'.$coacher_coachemail.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Coachens språk</div>
<div class="colB2"><input type="text" name="langs" value="'.$coacher_langs.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Bild</div>
<div class="colB2">
<input name="file" type="hidden" value="'.$coacher_file.'"/>
<a title="Lägg till bild" class="formbut" href="#" onclick="imagewin(\'images.php?action=getfile&whatform=form_18&basedir=&directory=bilder&area=file&pre_cell=file_cell\');return false;">Lägg till bild</a>
<a title="Ta bort bild" class="formbut" name="rfile" href="#rfile" onclick="document.form_18.file.value=\'\';document.file_cell.src=\'img/blank.gif\'">Ta bort bild</a>
<br/>
<img name="file_cell" src="../magick.php/'.$coacher_file.'?resize(135x150)"/>
</div>
</div>


<div class="rowAB">
<div class="colA2">Svensk presentation</div>
<div class="colB2x"><textarea name="sv_text" class="coachtext" onfocus="document.form_18.sv_text.style.height=\'210px\';document.form_18.en_text.style.height=\'210px\'" onblur="document.form_18.sv_text.style.height=\'30px\';document.form_18.en_text.style.height=\'30px\'">'.$coacher_sv_text.'</textarea></div>
</div>

<div class="rowAB">
<div class="colA2">Engelsk presentation</div>
<div class="colB2x"><textarea name="en_text" class="coachtext" onfocus="document.form_18.sv_text.style.height=\'210px\';document.form_18.en_text.style.height=\'210px\'" onblur="document.form_18.sv_text.style.height=\'30px\';document.form_18.en_text.style.height=\'30px\'">'.$coacher_en_text.'</textarea></div>
</div>

<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="coacher_CoachID" value="'.$coacher_CoachID.'"/>
<input type="hidden" name="delval" value=""/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="update"/>
<input type="button" class="submit" onclick="document.form_18.submit()" value="Spara ändringar"/> <br/><br/>
<input type="button" class="submit" name="dodelete" onclick="document.form_18.delval.value='.$coacher_CoachID.';document.form_18.key.value=\'delete\';document.form_18.submit();" value="Ta bort coachen"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

//////////////////////////////////////
// FORETAG select
$query = "SELECT ID, Foretagsnamn FROM foretag";
$results = mysql_query($query) or die(mysql_error());
if($action == "formular_edit" AND $grupper_GruppID){ $query2 = "SELECT FORETAG FROM grupptabell WHERE ID = ".$grupper_GruppID;
$query2 = sprintf($query2);
$results2 = mysql_fetch_array(mysql_query($query2)) or die(mysql_error());
}
while ($rows=mysql_fetch_array($results)) { 
	extract($rows,EXTR_PREFIX_ALL,"F");
	if($results2[0] and $F_ID == $results2[0]) $Fselect .= '<option value="'.$F_ID.'" selected="selected">'.$F_Foretagsnamn.'</option>'; else $Fselect .= '<option value="'.$F_ID.'">'.$F_Foretagsnamn.'</option>';
	}


$formular_19 = '
<form name="form_19" class="formz" method="post">
<br/><br/>
<strong>Skapa ny grupp</strong><br/><br/>

<div class="rowAB">
<div class="colA2">Företag</div>
<div class="colB2">
<select name="FORETAG" class="selector"> <option value="">Välj företag >></option> '.$Fselect.' </select></div>
</div>

<div class="rowAB">
<div class="colA2">Gruppnamn</div>
<div class="colB2"><input type="text" name="gruppnamn" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Grupplogin</div>
<div class="colB2">
<input type="text" name="grupplogin" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Grupplösenord</div>
<div class="colB2"><input type="text" name="grupplosen" value=""/></div>
</div>

<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="insert"/>
<input type="button" class="submit" onclick="document.form_19.submit()" value="Spara ny Grupp"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

//////////////////////////////////////
$formular_edit_19 = '
<form name="form_19" class="formz" method="post">
<br/><br/>
<strong>Ändra '.$grupper_gruppnamn.'</strong><br/><br/>

<div class="rowAB">
<div class="colA2">Företag</div>
<div class="colB2">
<select name="FORETAG" class="selector"> <option value="">Välj företag >></option> '.$Fselect.' </select></div>
</div>

<div class="rowAB">
<div class="colA2">Gruppnamn</div>
<div class="colB2"><input type="text" name="gruppnamn" value="'.$grupper_gruppnamn.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Grupplogin</div>
<div class="colB2">
<input type="text" name="grupplogin" value="'.$grupper_grupplogin.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Grupplösenord</div>
<div class="colB2"><input type="text" name="grupplosen" value="'.$grupper_grupplosen.'"/></div>
</div>

<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="grupper_GruppID" value="'.$grupper_GruppID.'"/>
<input type="hidden" name="delval" value=""/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="update"/>
<input type="button" class="submit" onclick="document.form_19.submit()" value="Spara ändringar"/> <br/><br/>
<input type="button" class="submit" name="dodelete" onclick="document.form_19.delval.value='.$grupper_GruppID.';document.form_19.key.value=\'delete\';document.form_19.submit();" value="Ta bort gruppen"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

//////////////////////////////////////
$formular_24 = '
<form name="form_24" class="formz" method="post">
<br/><br/>
<strong>Skapa ny chef</strong><br/><br/>

<div class="rowAB">
<div class="colA2">Chefnamn</div>
<div class="colB2"><input type="text" name="chefnamn" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Cheflogin</div>
<div class="colB2">
<input type="text" name="cheflogin" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Cheflösenord</div>
<div class="colB2"><input type="text" name="cheflosen" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Chefemail</div>
<div class="colB2"><input type="text" name="chefemail" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Superchef</div>
<div class="colB2"><input class="inputradio" type="checkbox" name="superchef" value="4"></div>
</div>

<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="insert"/>
<input type="button" class="submit" onclick="document.form_24.submit()" value="Spara ny Chef"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

if($chefer_ulvl > 2) $chefer_superchef = 'checked="checked"';

//////////////////////////////////////
$formular_edit_24 = '
<form name="form_24" class="formz" method="post">
<br/><br/>
<strong>Ändra '.$chefer_chefnamn.'</strong><br/><br/>

<div class="rowAB">
<div class="colA2">Chefnamn</div>
<div class="colB2"><input type="text" name="chefnamn" value="'.$chefer_chefnamn.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Cheflogin</div>
<div class="colB2">
<input type="text" name="cheflogin" value="'.$chefer_cheflogin.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Cheflösenord</div>
<div class="colB2"><input type="text" name="cheflosen" value="'.$chefer_cheflosen.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Chefemail</div>
<div class="colB2"><input type="text" name="chefemail" value="'.$chefer_chefemail.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Superchef</div>
<div class="colB2"><input class="inputradio" type="checkbox" name="superchef" value="4" '.$chefer_superchef.'/></div>
</div>

<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="chefer_ChefID" value="'.$chefer_ChefID.'"/>
<input type="hidden" name="delval" value=""/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="update"/>
<input type="button" class="submit" onclick="document.form_24.submit()" value="Spara ändringar"/> <br/><br/>
<input type="button" class="submit" name="dodelete" onclick="document.form_24.delval.value='.$chefer_ChefID.';document.form_24.key.value=\'delete\';document.form_24.submit();" value="Ta bort chefen"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

//////////////////////////////////////


//////////////////////////////////////
// FORETAG select
$query = "SELECT ID, Foretagsnamn FROM foretag";
$results = mysql_query($query) or die(mysql_error());
if($action == "formular_edit" AND $roller_RollID){ $query2 = "SELECT FORETAG FROM rolltabell WHERE ID = ".$roller_RollID;
$query2 = sprintf($query2);
$results2 = mysql_fetch_array(mysql_query($query2)) or die(mysql_error());
}
while ($rows=mysql_fetch_array($results)) { 
	extract($rows,EXTR_PREFIX_ALL,"rF");
	if($results2[0] and $rF_ID == $results2[0]) $rFselect .= '<option value="'.$rF_ID.'" selected="selected">'.$rF_Foretagsnamn.'</option>'; else $rFselect .= '<option value="'.$rF_ID.'">'.$rF_Foretagsnamn.'</option>';
	}


$formular_35 = '
<form name="form_35" class="formz" method="post">
<br/><br/>
<strong>Skapa ny roll</strong><br/><br/>

<div class="rowAB">
<div class="colA2">Företag</div>
<div class="colB2">
<select name="FORETAG" class="selector"> <option value="">Välj företag >></option> '.$rFselect.' </select></div>
</div>

<div class="rowAB">
<div class="colA2">Rollnamn</div>
<div class="colB2"><input type="text" name="rollnamn" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Roll-login</div>
<div class="colB2">
<input type="text" name="rolllogin" value=""/></div>
</div>

<div class="rowAB">
<div class="colA2">Roll-lösenord</div>
<div class="colB2"><input type="text" name="rolllosen" value=""/></div>
</div>

<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="insert"/>
<input type="button" class="submit" onclick="document.form_35.submit()" value="Spara ny Roll"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

//////////////////////////////////////
$formular_edit_35 = '
<form name="form_35" class="formz" method="post">
<br/><br/>
<strong>Ändra '.$roller_rollnamn.'</strong><br/><br/>

<div class="rowAB">
<div class="colA2">Företag</div>
<div class="colB2">
<select name="FORETAG" class="selector"> <option value="">Välj företag >></option> '.$Fselect.' </select></div>
</div>

<div class="rowAB">
<div class="colA2">Rollnamn</div>
<div class="colB2"><input type="text" name="rollnamn" value="'.$roller_rollnamn.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Roll-login</div>
<div class="colB2">
<input type="text" name="rolllogin" value="'.$roller_rolllogin.'"/></div>
</div>

<div class="rowAB">
<div class="colA2">Roll-lösenord</div>
<div class="colB2"><input type="text" name="rolllosen" value="'.$roller_rolllosen.'"/></div>
</div>

<br/>
<div class="colA2"> &nbsp; </div>
<div class="colB2">
<input type="hidden" name="cat_id" value="'.$cat_id.'"/>
<input type="hidden" name="roller_RollID" value="'.$roller_RollID.'"/>
<input type="hidden" name="delval" value=""/>
<input type="hidden" name="key" value="42"/>
<input type="hidden" name="action" value="update"/>
<input type="button" class="submit" onclick="document.form_35.submit()" value="Spara ändringar"/> <br/><br/>
<input type="button" class="submit" name="dodelete" onclick="document.form_35.delval.value='.$roller_RollID.';document.form_35.key.value=\'delete\';document.form_35.submit();" value="Ta bort rollen"/> &nbsp; &nbsp; <br/><br/>
</div>
</form>
';

?>